name: mighty_plant_admin
description: A new Flutter application.

version: 2.0.0

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  #  firebase crashlytics analytics support
  firebase_crashlytics:
  firebase_analytics:
  firebase_core:
  firebase_auth:


  # Used for speed up the coding and font selection
  nb_utils:
  google_fonts:

  #  used for API calling and Showing Html data
  http:
  intl:
  crypto:
  html:
  flutter_html:
  url_launcher:

  #  Used for Images and icon
  cached_network_image:
  photo_view:
  flutter_vector_icons:
  flutter_speed_dial:
  flutter_staggered_grid_view:

#  Application information
  package_info_plus:

  #  Used for chart
  syncfusion_flutter_charts:

  # Bottom NavigationBar
  convex_bottom_bar:
  bottom_navy_bar:

  # State Management Technique
  mobx:
  flutter_mobx:

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # State Management Technique
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
#flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flags/
    - lang/




